data:
  data_path: './datasets/raw/market_insights_overview_5p.csv'
  categories_path: './datasets/raw/solr_categories_2021_11_29.csv'


experiment:
  tags:
    - market_insights
  save_sources_to_use: # Which sources the experiment should be saved to
    - 'disk'
    - 'neptune'

  checkpoint_save_location: './models/0_current_model_checkpoints/'
  log_model_every_n_epoch: 10

  # Possible metrics: MSE, MAE
  error_metrics:
    - 'MSE'
    - 'MAE'

  save_source:
    disk:
      model_save_location: './models/'

    neptune:
      project_id: 'sjsivertandsanderkk/Masteroppgave'
      # Set api token with env variable NEPTUNE_API_TOKEN
      #api_token: ${NEPTUNE_API_TOKEN}


model:
  # Model types: 'validation_model'. 'local_univariate_arima',
  model_type: 'local_univariate_arima'
  rng_seed: 42
  validation_model:
    placeholder: 0

  local_univariate_arima:
    training_size: 0.8
    model_structure:
      - time_series_id: 11573
        # seasonal order
        order:
          - 5 # p
          - 2 # d
          - 0 # q
