data:
  data_path: './datasets/raw/market_insights_overview_all_2022_02_14.csv'
  categories_path: './datasets/raw/solr_categories_all_2022_02_14.csv'

logger:
  log_level: 'INFO'
  log_file: './log_file.log' # Currently does nothing

experiment:
  tags:
    - market_insights
  save_sources_to_use: # Which sources the experiment should be saved to
    - 'disk'
    - 'neptune'

  checkpoint_save_location: './models/0_current_model_checkpoints/'
  log_model_every_n_epoch: 1

  # Possible metrics: MSE, MAE, MSE; MAE
  error_metrics:
    - 'SMAPE'
    - 'MASE'
    - 'MSE'
    - 'MAE'
    - 'OWA'

  save_source:
    disk:
      model_save_location: './models/'

    neptune:
      project_id: 'sjsivertandsanderkk/Masteroppgave'
      # Set api token with env variable NEPTUNE_API_TOKEN
      #api_token: ${NEPTUNE_API_TOKEN}


model:
  # Model types: 'validation_model'. 'local_univariate_arima',
  model_type: 'local_univariate_arima'
  rng_seed: 42

  validation_model:
    placeholder: 0

  local_univariate_arima:
    training_size: 0.8
    steps_to_predict: 1000 # High number to predict the whole test dataset
    multi_step_forecast: false # alternative is recursive single step
    # Ranges used for autotuning if --tune parameter is set
    hyperparameter_tuning_range:
      p: [1, 8]
      d: [1, 10]
      q: [1, 16]

    metric_to_use_when_tuning: 'MASE'

    model_structure:
      - time_series_id: 2
        # 1
        hyperparameters:
          p: 7
          d: 2
          q: 4

      - time_series_id: 26
        # 2
        hyperparameters:
          p: 4
          d: 1
          q: 1

      - time_series_id: 6
        # 3
        hyperparameters:
          p: 7
          d: 1
          q: 7

      - time_series_id: 9
        # 4
        hyperparameters:
          p: 3
          d: 1
          q: 1

      - time_series_id: 10
        # 5
        hyperparameters:
          p: 8
          d: 1
          q: 1
      - time_series_id: 11
        # 6
        hyperparameters:
          p: 5
          d: 1
          q: 15
      - time_series_id: 13
        # 7
        hyperparameters:
          p: 6
          d: 1
          q: 1
      - time_series_id: 20
        # 8
        hyperparameters:
          p: 4
          d: 1
          q: 3

      - time_series_id: 24
        # 9
        hyperparameters:
          p: 3
          d: 2
          q: 4

      - time_series_id: 27
        # 10
        hyperparameters:
          p: 8
          d: 1
          q: 7

      - time_series_id: 28
        # 11
        hyperparameters:
          p: 6
          d: 1
          q: 3

      - time_series_id: 29
        # 12
        hyperparameters:
          p: 3
          d: 1
          q: 2

      - time_series_id: 32
        # 13
        hyperparameters:
          p: 1
          d: 2
          q: 1

      - time_series_id: 33
        # 14
        hyperparameters:
          p: 8
          d: 1
          q: 9

      - time_series_id: 34
        # 15
        hyperparameters:
          p: 7
          d: 2
          q: 8

      - time_series_id: 39
        # 16
        hyperparameters:
          p: 1
          d: 2
          q: 3

      - time_series_id: 41
        # 17
        hyperparameters:
          p: 1
          d: 1
          q: 1

      - time_series_id: 51
        # 18
        hyperparameters:
          p: 5
          d: 2
          q: 6

      - time_series_id: 54
        # 19
        hyperparameters:
          p: 6
          d: 1
          q: 9

      - time_series_id: 22
        hyperparameters:
          # 20
          p: 4
          d: 1
          q: 3
