data:
  # data_path: './datasets/raw/market_insights_overview_all_2022_02_14.csv'
  #data_path: './datasets/raw/market_insights_overview_all_2021_11_12.csv'
  data_path: './datasets/raw/market_insights_overview_5p_full.csv'
  categories_path: './datasets/raw/solr_categories_all_16_09_2021.csv'
  # categories_path: './datasets/raw/solr_categories_all_2022_02_14.csv'

logger:
  log_level: 'INFO'
  log_file: './log-file.log' # Currently does nothing

use_gpu_if_available: false # Some experience indicate that GPU is slower

experiment:
  tags:
    - market_insights
  save_sources_to_use: # Which sources the experiment should be saved to
    - 'disk'
    # - 'neptune'

  checkpoint_save_location: './models/0_current_model_checkpoints/'
  log_model_every_n_epoch: 10

  # Possible metrics: MSE, MAE, MSE; MAE
  error_metrics:
    - 'MAE'
    - 'MASE'
    - 'MSE'
    - 'SMAPE'
    - 'MAPE'
    #- 'MASE_Periodic'

  save_source:
    disk:
      model_save_location: './models/'

    neptune:
      project_id: 'sjsivertandsanderkk/Masteroppgave'
      # Set api token with env variable NEPTUNE_API_TOKEN
      #api_token: ${NEPTUNE_API_TOKEN}


model:
  # Model types: 'validation_model'. 'local_univariate_arima', 'local_univariate_lstm', 'local_cnn_ae', 'local_cnn_ae_lstm'
  # global
  model_type: 'local_univariate_lstm'
  rng_seed: 42
  validation_model:
    placeholder: 0
  univariate_lstm:
    hyperparameter_tuning_range:
      hidden_size: [ 2, 100]
      number_of_layers: [ 1, 5]
      dropout: [ 0.0, 0.4 ]
      #optimizer_name: ['Adam', 'RMSprop']
      optimizer_name: ['RMSprop']
      #optimizer_name: ['Adam']
      learning_rate: [ 1e-7, 1e-2 ]
      number_of_epochs: [5, 40]
      batch_size: [32, 32]
      input_window_size: 10
      output_window_size: 7 # must be equal output_window_size
      multi_variable_nr: 1 # must be equal to number of variables used in multi variable (1 if uni variate)
      number_of_features: 1 # must be equal to number of features in data
      number_of_trials: 5000 # Number of tuning trials to run. The more the better.
      #time_to_tune_in_minutes: 6000  # Time to tune in minutes, If both number of trials or time to tune is set, first one to finnish.
      stateful_lstm: true

    global_model:
      parameters_for_all_models:
        # If int <= 1 then the testing set will be equal to output_window_size
        training_size: 50 # Number of samles in validation set
        input_window_size: 10
        output_window_size: 7
        multi_variable_nr: 1
        batch_size: 32
        number_of_epochs: 21
        stateful_lstm: yes
        should_shuffle_batches: no
        optimizer_name: RMSprop
        learning_rate: 0.00025783
        hidden_layer_size: 100
        dropout: 0.01773
        number_of_features: 1
        number_of_layers: 1
      datasets:
        - 11573
        - 11037
        # - 12322
        # - 11428
        # - 11850
        # - 11852
        # - 273
        # - 11036
        # - 11213

    local_model:
      common_parameters_for_all_models:
        # If int <= 1 then the testing set will be equal to output_window_size
         training_size: 50 # Number of samles in validation set
         input_window_size: 10
         output_window_size: 7
         multi_variable_nr: 1
         batch_size: 32
         number_of_epochs: 15
         stateful_lstm: yes
         should_shuffle_batches: no
         optimizer_name: RMSprop

      model_structure:
        # - time_series_id: 11573
        - time_series_id: 12322
        #- time_series_id: 12322
        # - time_series_id: 2
          learning_rate: 0.00013756
          hidden_layer_size: 94
          dropout: 0.21199
          number_of_features: 1
          number_of_layers: 1
        - time_series_id: 11428
          learning_rate: 0.00013756
          hidden_layer_size: 94
          dropout: 0.21199
          number_of_features: 1
          number_of_layers: 1
        - time_series_id: 11850
          learning_rate: 0.00013756
          hidden_layer_size: 94
          dropout: 0.21199
          number_of_features: 1
          number_of_layers: 1
        - time_series_id: 11852
          learning_rate: 0.00013756
          hidden_layer_size: 94
          dropout: 0.21199
          number_of_features: 1
          number_of_layers: 1
        - time_series_id: 273
          learning_rate: 0.00013756
          hidden_layer_size: 94
          dropout: 0.21199
          number_of_features: 1
          number_of_layers: 1
        - time_series_id: 11036
          learning_rate: 0.00013756
          hidden_layer_size: 94
          dropout: 0.21199
          number_of_features: 1
          number_of_layers: 1
        - time_series_id: 11213
          learning_rate: 0.00013756
          hidden_layer_size: 94
          dropout: 0.21199
          number_of_features: 1
          number_of_layers: 1
        # - time_series_id: 6
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 10
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 11
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 13
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 20
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 22
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 24
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 26
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 27
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 28
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 29
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 32
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 33
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 34
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 39
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 41
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 51
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2
        # - time_series_id: 54
        #   learning_rate: 0.000522
        #   hidden_layer_size: 86
        #   dropout: 0.0192
        #   number_of_features: 4
        #   number_of_layers: 2

  local_univariate_cnn_ae:
    common_parameters_for_all_models:
      training_size: 7
      input_window_size: 14
      output_window_size: 7
      multi_variable_nr: 1
      batch_size: 1
      number_of_epochs: 51
      optimizer_name: 'adam'
      loss: "mse"
      should_shuffle_batches: True

    model_structure:
      #- time_series_id: 11573
      - time_series_id: 12322
        learning_rate: 0.003
        encoder:
          - layer: "Conv1d"
            filters: 8
            kernel_size: 3
            activation: "relu"
          - layer: "MaxPool"
            size: 2
            padding: "valid"
          - layer: "Conv1d"
            filters: 16
            kernel_size: 3
        decoder:
          - layer: "Conv1d"
            kernel_size: 5
            filters: 8
            activation: "relu"
          - layer: "Conv1d"
            kernel_size: 3
            filters: 4
            activation: "relu"
          - layer: "Conv1d"
            kernel_size: 3
            filters: 1

  local_univariate_cnn_ae_lstm:
    common_parameters_for_all_models:
      should_shuffle_batches: True
      training_size: 7
      optimizer_name: 'Adam'
      loss: "mae"
      batch_size: 10
      epochs: 20
      number_of_epochs: 20
      input_window_size: 10
      output_window_size: 7
      multi_variable_nr: 1
      lstm-shared:
        input_window_size: 10
        output_window_size: 7
        multi_variable_nr: 1
        epochs: 26

    model_structure:
      - time_series_id: 12322
        lstm:
          optimizer_name: 'RMSprop'
          stateful_lstm: True
          loss: "mae"
          learning_rate: 7.88e-05
          hidden_layer_size: 14
          dropout: 0.132
          number_of_features: 1
          number_of_layers: 3
        ae:
          optimizer_name: 'Adam'
          loss: "mse"
          learning_rate: 0.003
          epochs: 20
        encoder:
          - layer: "Conv1d"
            filters: 8
            kernel_size: 3
            activation: "relu"
          - layer: "MaxPool"
            size: 2
            padding: "valid"
          - layer: "Conv1d"
            filters: 16
            kernel_size: 3
        decoder:
          - layer: "Conv1d"
            kernel_size: 5
            filters: 8
            activation: "relu"
          - layer: "Conv1d"
            kernel_size: 3
            filters: 4
            activation: "relu"
          - layer: "Conv1d"
            kernel_size: 3
            filters: 1


  local_univariate_arima:
    forecast_window_size: 7
    steps_to_predict: 7
    multi_step_forecast: true # alternative is recursive single step
    auto_arima: true
    # Ranges used for autotuning if --tune parameter is set
    hyperparameter_tuning_range:
      p: [1, 10]
      d: [1, 10]
      q: [1, 16]

    metric_to_use_when_tuning: 'MASE'
    #metric_to_use_when_tuning: 'MSE'

    model_structure:
      #- time_series_id: 11573
      - time_series_id: 11573
        # 1
        hyperparameters:
          p: 9
          d: 2
          q: 11
