data:
  data_path: './datasets/raw/market_insights_overview_5p.csv'
  categories_path: './datasets/raw/solr_categories_2021_11_29.csv'


experiment:
  save_sources_to_use: # Which sources the experiment should be saved to
    - 'disk'
    #- 'neptune'
  
  save_source:
    disk:
      model_save_location: './models/'

    neptune:
      project: 'sjsivertandsanderkk/Masteroppgave'
      api_token: ${NEPTUNE_API_TOKEN}


model:
  model_type: 'local_univariate_arima'
  rng_seed: 42
  local_univariate_arima:
    order:
      - 5 # p
      - 2 # d
      - 0 # q
    # seasonal_order:
    #   - 5 # p
    #   - 2 # d
    #   - 0 # q
