data:
  data_path: './datasets/raw/market_insights_overview_5p_full.csv'
  categories_path: './datasets/raw/solr_categories_all_2022_02_14.csv'


logger:
  log_level: 'INFO'
  log_file: './log_file.log' # Currently does nothing

experiment:
  tags:
    - market_insights
  save_sources_to_use: # Which sources the experiment should be saved to
    - 'disk'
      #- 'neptune'

  checkpoint_save_location: './models/0_current_model_checkpoints/'
  log_model_every_n_epoch: 10

  # Possible metrics: MSE, MAE, MSE; MAE
  error_metrics:
    - 'SMAPE'
    - 'MASE'
    - 'MSE'
    - 'MAE'
    - 'OWA'

  save_source:
    disk:
      model_save_location: './models/'

    neptune:
      project_id: 'sjsivertandsanderkk/Masteroppgave'
      # Set api token with env variable NEPTUNE_API_TOKEN
      #api_token: ${NEPTUNE_API_TOKEN}


model:
  # Model types: 'validation_model'. 'local_univariate_arima', 'local_univariate_lstm'
  model_type: 'local_univariate_lstm'
  rng_seed: 42
  validation_model:
    placeholder: 0

  local_univariate_lstm:
    hyperparameter_tuning_range:
      number_of_tuning_trials: 10
      hidden_size: [ 10, 200 ]
      number_of_layers: [ 1, 5 ]
      dropout: [ 0.0, 0.5 ]
      optimizer_name: ['Adam', 'SGD', 'RMSprop']
      learning_rate: [ 1e-5, 1e-1 ]
      number_of_epochs: [ 10, 200 ]
      batch_size: [ 1, 100 ]
      output_window_size: 1 # must be equal output_window_size
      number_of_features: 1 # must be equal to number of features in data

    common_parameters_for_all_models:
      training_size: 0.8
      input_window_size: 7
      output_window_size: 1
      batch_size: 32
      optimizer_name: 'SGD'

    model_structure:
      - time_series_id: 11573
        learning_rate: 0.001
        hidden_layer_size: 64
        dropout: 0.2
        number_of_features: 1
        number_of_layers: 1

  local_univariate_arima:
    training_size: 0.8
    steps_to_predict: 1000
    multi_step_forecast: false # alternative is recursive single step
    # Ranges used for autotuning if --tune parameter is set
    hyperparameter_tuning_range:
      p: [1, 8]
      d: [1, 10]
      q: [1, 16]

    metric_to_use_when_tuning: 'MASE'

    model_structure:
      - time_series_id: 2
        # 1
        hyperparameters:
          p: 7
          d: 2
          q: 7

      - time_series_id: 6
        # 2
        hyperparameters:
          p: 8
          d: 1
          q: 7

      - time_series_id: 9
        # 3
        hyperparameters:
          p: 8
          d: 1
          q: 16

      - time_series_id: 10
        # 4
        hyperparameters:
          p: 8
          d: 1
          q: 1

      - time_series_id: 11
        # 5
        hyperparameters:
          p: 7
          d: 1
          q: 6

      - time_series_id: 13
        # 6
        hyperparameters:
          p: 6
          d: 1
          q: 1

      - time_series_id: 20
        # 7
        hyperparameters:
          p: 2
          d: 2
          q: 6

      - time_series_id: 22
        # 8
        hyperparameters:
          p: 8
          d: 1
          q: 5

      - time_series_id: 24
        # 9
        hyperparameters:
          p: 3
          d: 2
          q: 4

      - time_series_id: 26
        # 10
        hyperparameters:
          p: 4
          d: 1
          q: 1

      - time_series_id: 27
        # 11
        hyperparameters:
          p: 8
          d: 1
          q: 7

      - time_series_id: 28
        # 12
        hyperparameters:
          p: 8
          d: 1
          q: 14

      - time_series_id: 29
        # 13
        hyperparameters:
          p: 3
          d: 1
          q: 2

      - time_series_id: 32
        # 14
        hyperparameters:
          p: 1
          d: 2
          q: 1

      - time_series_id: 33
        # 15
        hyperparameters:
          p: 8
          d: 1
          q: 6

      - time_series_id: 34
        # 16
        hyperparameters:
          p: 6
          d: 2
          q: 15

      - time_series_id: 39
        # 17
        hyperparameters:
          p: 1
          d: 2
          q: 3

      - time_series_id: 41
        # 18
        hyperparameters:
          p: 7
          d: 1
          q: 5

      - time_series_id: 51
        # 19
        hyperparameters:
          p: 4
          d: 1
          q: 12

      - time_series_id: 54
        hyperparameters:
          # 20
          p: 6
          d: 1
          q: 9
