data:
  data_path: './datasets/raw/market_insights_overview_all_2022_02_14.csv'
  categories_path: './datasets/raw/solr_categories_all_2022_02_14.csv'


logger:
  log_level: 'INFO'
  log_file: './log_file.log' # Currently does nothing

experiment:
  tags:
    - market_insights_2022_02_14
  save_sources_to_use: # Which sources the experiment should be saved to
    - 'disk'
    - 'neptune'

  checkpoint_save_location: './models/0_current_model_checkpoints/'
  log_model_every_n_epoch: 10

  # Possible metrics: MSE, MAE, MSE; MAE
  error_metrics:
    - 'SMAPE'
    - 'MASE'
    - 'MSE'
    - 'MAE'

  save_source:
    disk:
      model_save_location: './models/'

    neptune:
      project_id: 'sjsivertandsanderkk/Masteroppgave'
      # Set api token with env variable NEPTUNE_API_TOKEN
      #api_token: ${NEPTUNE_API_TOKEN}


model:
  # Model types: 'validation_model'. 'local_univariate_arima',
  model_type: 'local_univariate_arima'
  rng_seed: 42
  validation_model:
    placeholder: 0

  local_univariate_arima:
    training_size: 0.8
    steps_to_predict: 20
    multi_step_forecast: false # alternative is recursive single step
    # Ranges used for autotuning if --tune parameter is set
    hyperparameter_tuning_range:
      p: [1, 2]
      d: [1, 2]
      q: [1, 2]

    metric_to_use_when_tuning: 'SMAPE'

    model_structure:
      - time_series_id: 2
        # 1
        # bærbar pc
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 6
        # 2
        # digitalkamera
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 9
        # 3
        # hardisk og ssd
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 10
        # 4
        # hovedkort
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11
        # 5
        # pc høyttalere
        hyperparameters:
          p: 8
          d: 8
          q: 16
      - time_series_id: 13
        # 6
        # kabinett
        hyperparameters:
          p: 8
          d: 8
          q: 16
      - time_series_id: 20
        # 7
        # mp3 spiller
        hyperparameters:
          p: 8
          d: 8
          q: 16
      - time_series_id: 22
        # 8
        # mus
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 24
        # 9
        # objektiv
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 26
        # 10
        # projektor
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 27
        # 11
        # minne ram
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 28
        # 12
        # skanner
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 29
        # 13
        # pc skjerm
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 32
        # 14
        # spill
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 33
        # 15
        # Tastatur
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 34
        # 15
        # Videokamera
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 39
        # 17
        # Diverse spillutstyr
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 41
        # 18
        # Programvar
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 51
        # 19
        # Hodetelefoner
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 54
        # 20
        # Systemkamera
        hyperparameters:
          # 20
          p: 8
          d: 8
          q: 16
