data:
  data_path: './datasets/raw/market_insights_overview_all_2022_02_14.csv'
  categories_path: './datasets/raw/solr_categories_all_2022_02_14.csv'
  data_path: 'datasets/raw/market_insights_overview_5p_full.csv'
  categories_path: 'datasets/raw/solr_categories_2021_11_29.csv'

logger:
  log_level: 'INFO'
  log_file: './log_file.log' # Currently does nothing

experiment:
  tags:
    - market_insights
  save_sources_to_use: # Which sources the experiment should be saved to
    - 'disk'
    - 'neptune'

  checkpoint_save_location: './models/0_current_model_checkpoints/'
  log_model_every_n_epoch: 10

  # Possible metrics: MSE, MAE, MSE; MAE
  error_metrics:
    - 'SMAPE'
    - 'MASE'
    - 'MSE'
    - 'MAE'
    - 'OWA'

  save_source:
    disk:
      model_save_location: './models/'

    neptune:
      project_id: 'sjsivertandsanderkk/Masteroppgave'
      # Set api token with env variable NEPTUNE_API_TOKEN
      #api_token: ${NEPTUNE_API_TOKEN}


model:
  # Model types: 'validation_model'. 'local_univariate_arima', 'local_univariate_lstm'
  model_type: 'local_univariate_lstm'
  rng_seed: 42
  validation_model:
    placeholder: 0

  local_univariate_lstm:
    training_size: 0.8
    input_window_size: 7
    output_window_size: 1
    number_of_tuning_trials: 10
    hyperparameter_tuning_range:
      hidden_size: (10, 200)
      num_layers: (1, 5)
      dropout: (0.0, 0.5)
      optimizer_name: ['Adam', 'SGD', 'RMSprop']
      learning_rate: (1e-5, 1e-1)
      number_of_epochs: (10, 200)
      number_of_features: 1
      batch_size: (1, 100)
      output_size: 1 # must be equal output_window_size

    model_structure:
      - time_series_id: 12532
        # 1
      - time_series_id: 11694
        # 2
      - time_series_id: 11716
        # 3
      - time_series_id: 11950
        # 4
      - time_series_id: 11195
        # 5
      - time_series_id: 11998
        # 6
      - time_series_id: 274
        # 7
      - time_series_id: 11407
        # 8

      - time_series_id: 46
        # 9

      - time_series_id: 11326
        # 10

      - time_series_id: 11335
        # 11

      - time_series_id: 12197
        # 12
      - time_series_id: 11693
        # 13
      - time_series_id: 11780
        # 14
      - time_series_id: 12502
        # 15
      - time_series_id: 11866
        # 16
      - time_series_id: 11400
        # 17
      - time_series_id: 12256
        # 18
      - time_series_id: 10320
        # 19
      - time_series_id: 10030

  local_univariate_arima:
    training_size: 0.8
    steps_to_predict: 20
    multi_step_forecast: false # alternative is recursive single step
    # Ranges used for autotuning if --tune parameter is set
    hyperparameter_tuning_range:
      p: [1, 2]
      d: [1, 2]
      q: [1, 2]

    metric_to_use_when_tuning: 'SMAPE'

    model_structure:
      - time_series_id: 12532
        # 1
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11694
        # 2
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11716
        # 3
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11950
        # 4
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11195
        # 5
        hyperparameters:
          p: 8
          d: 8
          q: 16
      - time_series_id: 11998
        # 6
        hyperparameters:
          p: 8
          d: 8
          q: 16
      - time_series_id: 274
        # 7
        hyperparameters:
          p: 8
          d: 8
          q: 16
      - time_series_id: 11407
        # 8
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 46
        # 9
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11326
        # 10
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11335
        # 11
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 12197
        # 12
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11693
        # 13
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11780
        # 14
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 12502
        # 15
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11866
        # 16
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11400
        # 17
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 12256
        # 18
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 10320
        # 19
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 10030
        hyperparameters:
          # 20
          p: 8
          d: 8
          q: 16