raport:
  table_save_location: '../MScTemplate/tables/code_generated/data_exploration/'
  figure_save_location: '../MScTemplate/figs/code_generated/data_exploration/'

data:
  data_path: './datasets/categories_1000.csv'
