data:
  data_path: './datasets/raw/market_insights_overview_5p.csv'
  categories_path: './datasets/raw/solr_categories_2021_11_29.csv'


experiment:
  tags:
    - market_insights
  save_sources_to_use: # Which sources the experiment should be saved to
    - 'disk'
    - 'neptune'
  
  save_source:
    disk:
      model_save_location: './models/'
      checkpoint_save_location: './models/0_current_model_checkpoints/'
      log_model_every_n_epoch: 10

    neptune:
      project_id: 'sjsivertandsanderkk/Masteroppgave'
      # Set api token with env variable NEPTUNE_API_TOKEN
      #api_token: ${NEPTUNE_API_TOKEN}


model:
  # Model types: 'validation_model'. 'local_univariate_arima',
  model_type: 'validation_model'
  rng_seed: 42
  validation_model:
    placeholder: 0
  local_univariate_arima:
    order:
      - 5 # p
      - 2 # d
      - 0 # q
    # seasonal_order:
    #   - 5 # p
    #   - 2 # d
    #   - 0 # q
