data:
  data_path: './datasets/raw/market_insights_overview_5p_full.csv'
  categories_path: './datasets/raw/solr_categories_2021_11_29.csv'


logger:
  log_level: 'INFO'
  log_file: './log_file.log' # Currently does nothing

experiment:
  tags:
    - market_insights
  save_sources_to_use: # Which sources the experiment should be saved to
    - 'disk'
    # - 'neptune'

  checkpoint_save_location: './models/0_current_model_checkpoints/'
  log_model_every_n_epoch: 10

  # Possible metrics: MSE, MAE, MSE; MAE
  error_metrics:
    - 'SMAPE'
    - 'MASE'
    - 'MSE'
    - 'MAE'

  save_source:
    disk:
      model_save_location: './models/'

    neptune:
      project_id: 'sjsivertandsanderkk/Masteroppgave'
      # Set api token with env variable NEPTUNE_API_TOKEN
      #api_token: ${NEPTUNE_API_TOKEN}


model:
  # Model types: 'validation_model'. 'local_univariate_arima',
  model_type: 'local_univariate_arima'
  rng_seed: 42
  validation_model:
    placeholder: 0

  local_univariate_arima:
    training_size: 0.8
    steps_to_predict: 20
    multi_step_forecast: false # alternative is recursive single step
      # Ranges used for autotuning if --tune parameter is set
    hyperparameter_tuning_range:
      p: [1, 8]
      d: [1, 8]
      q: [1, 11]

    metric_to_use_when_tuning: 'SMAPE'

    model_structure:
      - time_series_id: 11573
        # seasonal order
        hyperparameters:
          p: 8
          d: 8
          q: 16

      - time_series_id: 11037
        hyperparameters:
          p: 8
          d: 8
          q: 16
