[tool.black]
line-length = 100
include ='\.pyi?$'
# Explude pipeline files from formatting because it is ugly
exclude = '''
/(
	\*_pipeline.py
	|\.toml
	|\.md
	|\.yaml
	|\.txt
	|\.sh
	|\.git
	|\.ini
	|\.ipynb
	|\.tex
 )/
'''
