model:
    rng_seed: 42
    model_type: local_cnn_ae_lstm
    model_config:
        hyperparameter_tuning_range:
            hidden_size: [1, 100]
            number_of_layers: [1, 2]
            dropout: [0.0, 0.4]
            recurrent_dropout: [0.0, 0.4]
            optimizer_name: [RMSprop, Adam]
            learning_rate: [1e-7, 1e-2]
            number_of_epochs: [1, 40]
            batch_size: [32, 32]
            input_window_size: 10
            output_window_size: 7
            multi_variable_nr: 1
            number_of_features: 1
            number_of_trials: 200
            stateful_lstm: yes
        common_parameters_for_all_models:
            should_shuffle_batches: no
            batch_size: 32
            input_window_size: 10
            output_window_size: 7
            multi_variable_nr: 4
            lstm-shared:
                input_window_size: 10
                output_window_size: 7
                multi_variable_nr: 4
                batch_size: 32
                epochs: 9
                layers: &id001 [{dropout: 0.3051754834430947, hidden_size: 43, recurrent_dropout: 0.25730123032272506}]
                learning_rate: 0.00215172439953498
                number_of_features: 4
                optimizer_name: Adam
                stateful_lstm: yes
            ae:
                optimizer_name: Adam
                loss: mae
                learning_rate: 0.0001
                epochs: 70
            encoder: [{layer: Conv1d, filters: 16, kernel_size: 3, activation: relu}, {layer: Conv1d, filters: 32, kernel_size: 5, activation: relu}]
            decoder: [{layer: Conv1dTranspose, kernel_size: 5, filters: 32, activation: relu}, {layer: Conv1dTranspose, kernel_size: 3, filters: 4}]
        model_structure:
        -   lstm:
                batch_size: 32
                epochs: 1
                layers: [{dropout: 0.07964238549642215, hidden_size: 73, recurrent_dropout: 0.20237159756417045}, {dropout: 0.24824851894436017, hidden_size: 73, recurrent_dropout: 0.2719272087668037}]
                learning_rate: 0.0006890918655991167
                number_of_features: 4
                optimizer_name: RMSprop
                stateful_lstm: yes
            time_series_id: 12322
        -   lstm:
                batch_size: 32
                epochs: 12
                layers: [{dropout: 0.15910976971419502, hidden_size: 43, recurrent_dropout: 0.1831500542555661}, {dropout: 0.27843717947685387, hidden_size: 28, recurrent_dropout: 0.2383856811570707}]
                learning_rate: 0.002968169180594408
                number_of_features: 4
                optimizer_name: RMSprop
                stateful_lstm: yes
            time_series_id: 11428
        -   lstm:
                batch_size: 32
                epochs: 11
                layers: [{dropout: 0.04560968036143749, hidden_size: 92, recurrent_dropout: 0.12540250076320963}]
                learning_rate: 0.0008772965492642223
                number_of_features: 4
                optimizer_name: RMSprop
                stateful_lstm: yes
            time_series_id: 11850
        -   lstm:
                batch_size: 32
                epochs: 27
                layers: [{dropout: 0.03309202619016266, hidden_size: 86, recurrent_dropout: 0.14217557334003683}]
                learning_rate: 0.0015136309664057384
                number_of_features: 4
                optimizer_name: Adam
                stateful_lstm: yes
            time_series_id: 11852
        -   lstm:
                batch_size: 32
                epochs: 31
                layers: [{dropout: 0.08741745559159386, hidden_size: 86, recurrent_dropout: 0.32095844986704114}]
                learning_rate: 0.0006483929165427948
                number_of_features: 4
                optimizer_name: RMSprop
                stateful_lstm: yes
            time_series_id: 273
        -   lstm:
                batch_size: 32
                epochs: 8
                layers: [{dropout: 0.0712732264374839, hidden_size: 24, recurrent_dropout: 0.07817436504416779}]
                learning_rate: 0.0039171776048051435
                number_of_features: 4
                optimizer_name: Adam
                stateful_lstm: yes
            time_series_id: 11036
        -   lstm:
                batch_size: 32
                epochs: 18
                layers: [{dropout: 0.056286201458401235, hidden_size: 70, recurrent_dropout: 0.39727186599343167}]
                learning_rate: 0.006270921699587954
                number_of_features: 4
                optimizer_name: RMSprop
                stateful_lstm: yes
            time_series_id: 11213
        -   lstm:
                batch_size: 32.0
                epochs: 9
                layers: *id001
                learning_rate: 0.00215172439953498
                number_of_features: 4
                optimizer_name: Adam
                stateful_lstm: yes
            time_series_id: 12532
        placeholder: yes
    config: local_cnn_ae_lstm/dataset-seasonal-multivariate-tuned
    validation_model:
        placeholder: yes
data:
    data_path: ./datasets/raw/market_insights_overview_all_2022_04_26_filtered.csv
    categories_path: ./datasets/raw/solr_categories_all_2022_02_14.csv
logger:
    log_level: INFO
    log_file: ./log-file.log
use_gpu_if_available: no
experiment:
    tags: [market_insights]
    save_sources_to_use: [disk, neptune]
    checkpoint_save_location: ./models/0_current_model_checkpoints/
    log_model_every_n_epoch: 10
    error_metrics:
    - MAE
    - MASE
    - MSE
    - MAPE
    save_source:
        disk:
            model_save_location: ./models/
        neptune:
            project_id: sjsivertandsanderkk/Masteroppgave
