model:
  rng_seed: 42
  model_type: 'local_cnn_ae_lstm'
  model_config:
    hyperparameter_tuning_range:
      hidden_size: [ 1, 100 ]
      number_of_layers: [ 1, 2 ]
      dropout: [ 0.0, 0.4 ]
      recurrent_dropout: [0.0, 0.4]
      optimizer_name: [ 'RMSprop', 'Adam' ]
      learning_rate: [ 1e-7, 1e-2 ]
      number_of_epochs: [ 1, 40 ]
      batch_size: [ 32, 32 ]
      input_window_size: 10
      output_window_size: 7 # must be equal output_window_size
      multi_variable_nr: 1 # must be equal to number of variables used in multi variable (1 if uni variate)
      number_of_features: 1 # must be equal to number of features in data
      number_of_trials: 200 # Number of tuning trials to run. The more the better.
      #time_to_tune_in_minutes: 6000  # Time to tune in minutes, If both number of trials or time to tune is set, first one to finnish.
      stateful_lstm: true
    common_parameters_for_all_models:
      should_shuffle_batches: False
      batch_size: 32
      input_window_size: 10
      output_window_size: 7
      multi_variable_nr: 1
      lstm-shared:
        input_window_size: 10
        output_window_size: 7
        multi_variable_nr: 1
      ae:
        optimizer_name: 'Adam'
        loss: "mae"
        learning_rate: 0.0001
        epochs: 70
      encoder:
        - layer: "Conv1d"
          filters: 16
          kernel_size: 3
          activation: "relu"
        - layer: "Conv1d"
          filters: 32
          kernel_size: 5
          activation: "relu"
      decoder:
        - layer: "Conv1dTranspose"
          kernel_size: 5
          filters: 32
          activation: "relu"
        - layer: "Conv1dTranspose"
          kernel_size: 3
          filters: 1


    model_structure:
      - lstm:
          batch_size: 32
          epochs: 14
          layers:
          - dropout: 0.15100020954547821
            hidden_size: 91
            recurrent_dropout: 0.22863347633617925
          learning_rate: 0.0016105715885643915
          number_of_features: 1
          optimizer_name: Adam
          stateful_lstm: true
        time_series_id: 12322
      - lstm:
          batch_size: 32
          epochs: 11
          layers:
          - dropout: 0.39336919296578254
            hidden_size: 64
            recurrent_dropout: 0.08636761131328473
          learning_rate: 0.0011792422872227873
          number_of_features: 1
          optimizer_name: RMSprop
          stateful_lstm: true
        time_series_id: 11428
      - lstm:
          batch_size: 32
          epochs: 1
          layers:
          - dropout: 0.21560019556086574
            hidden_size: 100
            recurrent_dropout: 0.36609937865144704
          learning_rate: 0.00014313781377529085
          number_of_features: 1
          optimizer_name: Adam
          stateful_lstm: true
        time_series_id: 11850
      - lstm:
          batch_size: 32
          epochs: 5
          layers:
          - dropout: 0.07734056811928544
            hidden_size: 95
            recurrent_dropout: 0.17669206672675236
          learning_rate: 0.0005054774818177908
          number_of_features: 1
          optimizer_name: Adam
          stateful_lstm: true
        time_series_id: 11852
      - lstm:
          batch_size: 32
          epochs: 32
          layers:
          - dropout: 0.3993479833051537
            hidden_size: 18
            recurrent_dropout: 0.18669880207694867
          learning_rate: 0.0014733395482158461
          number_of_features: 1
          optimizer_name: Adam
          stateful_lstm: true
        time_series_id: 273
      - lstm:
          batch_size: 32
          epochs: 17
          layers:
          - dropout: 0.347011442668677
            hidden_size: 19
            recurrent_dropout: 0.24225463086014892
          learning_rate: 0.008437731251170208
          number_of_features: 1
          optimizer_name: Adam
          stateful_lstm: true
        time_series_id: 11036
      - lstm:
          batch_size: 32
          epochs: 22
          layers:
          - dropout: 0.21584111272429723
            hidden_size: 95
            recurrent_dropout: 0.2492641599857594
          learning_rate: 0.005031288075914328
          number_of_features: 1
          optimizer_name: Adam
          stateful_lstm: true
        time_series_id: 11213
      - lstm:
          batch_size: 32
          epochs: 1
          layers:
          - dropout: 0.010346524530866503
            hidden_size: 100
            recurrent_dropout: 0.3456684451624259
          learning_rate: 0.0004914914886714536
          number_of_features: 1
          optimizer_name: RMSprop
          stateful_lstm: true
        time_series_id: 12532
