model:
  rng_seed: 42
  model_type: 'local_cnn_ae_lstm'
  model_config:
    hyperparameter_tuning_range:
      hidden_size: [ 1, 100 ]
      number_of_layers: [ 1, 2 ]
      dropout: [ 0.0, 0.4 ]
      recurrent_dropout: [0.0, 0.4]
      optimizer_name: [ 'RMSprop', 'Adam' ]
      learning_rate: [ 1e-7, 1e-2 ]
      number_of_epochs: [ 1, 40 ]
      batch_size: [ 32, 32 ]
      input_window_size: 40
      output_window_size: 30 # must be equal output_window_size
      multi_variable_nr: 1 # must be equal to number of variables used in multi variable (1 if uni variate)
      number_of_features: 1 # must be equal to number of features in data
      number_of_trials: 500 # Number of tuning trials to run. The more the better.
      #time_to_tune_in_minutes: 6000  # Time to tune in minutes, If both number of trials or time to tune is set, first one to finnish.
      stateful_lstm: true
    common_parameters_for_all_models:
      should_shuffle_batches: False
      batch_size: 32
      input_window_size: 40
      output_window_size: 30
      multi_variable_nr: 1
      lstm-shared:
        input_window_size: 40
        output_window_size: 30
        multi_variable_nr: 1

    model_structure:
      # Data Series 2
      - time_series_id: 2
        lstm:
          stateful_lstm: True
          optimizer_name: 'RMSprop'
          loss: "mae"
          learning_rate: 0.000123319
          number_of_features: 1
          epochs: 20
          layers:
            - hidden_size: 84
              dropout: 0.011609
              recurrent_dropout: 0.145647
            - hidden_size: 94
              dropout: 0.20344
              recurrent_dropout: 0.3804909
        ae:
          optimizer_name: 'Adam'
          loss: "mae"
          learning_rate: 0.0001
          epochs: 100
        encoder:
          - layer: "Conv1d"
            filters: 16
            kernel_size: 7
            activation: "relu"
          - layer: "Conv1d"
            filters: 16
            kernel_size: 9
            activation: "relu"
        decoder:
          - layer: "Conv1dTranspose"
            kernel_size: 9
            filters: 16
            activation: "relu"
          - layer: "Conv1dTranspose"
            kernel_size: 7
            filters: 1

      # Data Series 6
      - time_series_id: 6
        lstm:
          optimizer_name: 'RMSprop'
          stateful_lstm: True
          loss: "mae"
          learning_rate: 0.0004707068
          number_of_features: 1
          epochs: 29
          layers:
            - hidden_size: 39
              dropout: 0.3368706
              recurrent_dropout: 0.2348005
        ae:
          optimizer_name: 'Adam'
          loss: "mae"
          learning_rate: 0.0001
          epochs: 100
        encoder:
          - layer: "Conv1d"
            filters: 16
            kernel_size: 7
            activation: "relu"
          - layer: "Conv1d"
            filters: 16
            kernel_size: 9
            activation: "relu"
        decoder:
          - layer: "Conv1dTranspose"
            kernel_size: 9
            filters: 16
            activation: "relu"
          - layer: "Conv1dTranspose"
            kernel_size: 7
            filters: 1

      # Data Series 9
      - time_series_id: 9
        lstm:
          optimizer_name: 'RMSprop'
          stateful_lstm: True
          loss: "mae"
          learning_rate: 0.000840387298
          number_of_features: 1
          epochs: 16
          layers:
            - hidden_size: 24
              dropout: 0.00062984
              recurrent_dropout: 0.3757795967
        ae:
          optimizer_name: 'Adam'
          loss: "mae"
          learning_rate: 0.0001
          epochs: 100
        encoder:
          - layer: "Conv1d"
            filters: 16
            kernel_size: 7
            activation: "relu"
          - layer: "Conv1d"
            filters: 16
            kernel_size: 9
            activation: "relu"
        decoder:
          - layer: "Conv1dTranspose"
            kernel_size: 9
            filters: 16
            activation: "relu"
          - layer: "Conv1dTranspose"
            kernel_size: 7
            filters: 1

      # Data Series 10
      - time_series_id: 10
        lstm:
          optimizer_name: 'RMSprop'
          stateful_lstm: True
          loss: "mae"
          learning_rate: 0.0014748521468404662
          number_of_features: 1
          epochs: 4
          layers:
            - hidden_size: 80
              dropout: 0.253187256787
              recurrent_dropout: 0.3752092266
        ae:
          optimizer_name: 'Adam'
          loss: "mae"
          learning_rate: 0.0001
          epochs: 100
        encoder:
          - layer: "Conv1d"
            filters: 16
            kernel_size: 7
            activation: "relu"
          - layer: "Conv1d"
            filters: 16
            kernel_size: 9
            activation: "relu"
        decoder:
          - layer: "Conv1dTranspose"
            kernel_size: 9
            filters: 16
            activation: "relu"
          - layer: "Conv1dTranspose"
            kernel_size: 7
            filters: 1

      # Data Series 11
      - time_series_id: 11
        lstm:
          optimizer_name: 'RMSprop'
          stateful_lstm: True
          loss: "mae"
          learning_rate: 0.0033873287
          number_of_features: 1
          epochs: 3
          layers:
            - hidden_size: 15
              dropout: 0.06573998
              recurrent_dropout: 0.133365756
        ae:
          optimizer_name: 'Adam'
          loss: "mae"
          learning_rate: 0.0001
          epochs: 100
        encoder:
          - layer: "Conv1d"
            filters: 16
            kernel_size: 5
            activation: "relu"
          - layer: "Conv1d"
            filters: 32
            kernel_size: 9
            activation: "relu"
        decoder:
          - layer: "Conv1dTranspose"
            kernel_size: 9
            filters: 32
            activation: "relu"
          - layer: "Conv1dTranspose"
            kernel_size: 5
            filters: 1

      # Data Series 13
      - time_series_id: 13
        lstm:
          optimizer_name: 'Adam'
          stateful_lstm: True
          loss: "mae"
          learning_rate: 0.000409735
          number_of_features: 1
          epochs: 16
          layers:
            - hidden_size: 85
              dropout: 0.019903239
              recurrent_dropout: 0.14670325
        ae:
          optimizer_name: 'Adam'
          loss: "mae"
          learning_rate: 0.0001
          epochs: 100
        encoder:
          - layer: "Conv1d"
            filters: 16
            kernel_size: 5
            activation: "relu"
          - layer: "Conv1d"
            filters: 32
            kernel_size: 9
            activation: "relu"
        decoder:
          - layer: "Conv1dTranspose"
            kernel_size: 9
            filters: 32
            activation: "relu"
          - layer: "Conv1dTranspose"
            kernel_size: 5
            filters: 1

      # Data Series 20
      - time_series_id: 20
        lstm:
          optimizer_name: 'RMSprop'
          stateful_lstm: True
          loss: "mae"
          learning_rate: 0.00617737261855
          number_of_features: 1
          epochs: 22
          layers:
            - hidden_size: 3
              dropout: 0.0179576858
              recurrent_dropout: 0.080991248985
        ae:
          optimizer_name: 'Adam'
          loss: "mae"
          learning_rate: 0.0001
          epochs: 100
        encoder:
          - layer: "Conv1d"
            filters: 16
            kernel_size: 5
            activation: "relu"
          - layer: "Conv1d"
            filters: 32
            kernel_size: 9
            activation: "relu"
        decoder:
          - layer: "Conv1dTranspose"
            kernel_size: 9
            filters: 32
            activation: "relu"
          - layer: "Conv1dTranspose"
            kernel_size: 5
            filters: 1
