model:
    model_config:
        local_model:
            model_structure: [{batch_size: 32, learning_rate: 0.002098645277731363, number_of_epochs: 1, number_of_layers: 2, optimizer_name: RMSprop, time_series_id: 10030, layers: [{hidden_size: 80, dropout: 0.3355141179557744, recurrent_dropout: 0.2523514028223536}, {hidden_size: 90, dropout: 0.02315427439174607, recurrent_dropout: 0.3123171963798159}]}]
            common_parameters_for_all_models:
                input_window_size: 10
                output_window_size: 7
                multi_variable_nr: 4
                batch_size: 32
                stateful_lstm: yes
                should_shuffle_batches: no
                number_of_features: 4
        hyperparameter_tuning_range:
            hidden_size: [1, 100]
            number_of_layers: [1, 2]
            dropout: [0.0, 0.4]
            recurrent_dropout: [0.0, 0.4]
            optimizer_name: [RMSprop, Adam]
            learning_rate: [1e-7, 1e-2]
            number_of_epochs: [1, 40]
            batch_size: [32, 32]
            input_window_size: 10
            output_window_size: 7
            multi_variable_nr: 4
            number_of_features: 4
            number_of_trials: 400
            stateful_lstm: yes
        global_model:
            model_structure:
                input_window_size: 10
                output_window_size: 7
                multi_variable_nr: 4
                batch_size: 32
                number_of_epochs: 40
                stateful_lstm: yes
                should_shuffle_batches: no
                optimizer_name: RMSprop
                learning_rate: 0.0010480378531841522
                number_of_features: 4
                layers: [{hidden_size: 97, dropout: 0.07577543324992782, recurrent_dropout: 0.3860940444331956}, {hidden_size: 41, dropout: 0.23565282953964958, recurrent_dropout: 0.05715033086301391}]
            datasets:
            - 12532
            - 11694
            - 11716
            - 11950
            - 11195
            - 11998
            - 274
            - 11407
            - 46
            - 11326
            - 11335
            - 12197
            - 11693
            - 11780
            - 12502
            - 11866
            - 11400
            - 12256
            - 10320
            - 10030
        placeholder: yes
    rng_seed: 42
    model_type: local_univariate_lstm
    config: multi_lstm/dataset-2
    validation_model:
        placeholder: yes
data:
    data_path: ./datasets/raw/market_insights_overview_all_2022_04_26_filtered.csv
    categories_path: ./datasets/raw/solr_categories_all_2022_02_14.csv
logger:
    log_level: INFO
    log_file: ./log-file.log
use_gpu_if_available: no
experiment:
    tags: [market_insights]
    save_sources_to_use: [disk, neptune]
    checkpoint_save_location: ./models/0_current_model_checkpoints/
    log_model_every_n_epoch: 10
    error_metrics:
    - MAE
    - MASE
    - MSE
    - MAPE
    save_source:
        disk:
            model_save_location: ./models/
        neptune:
            project_id: sjsivertandsanderkk/Masteroppgave
