model:
  rng_seed: 42
  model_type: 'local_univariate_arima'
  model_config:
    forecast_window_size: 7
    steps_to_predict: 7
    multi_step_forecast: true # alternative is recursive single step
    auto_arima: true
    seasonal: true
    # Ranges used for autotuning if --tune parameter is set
    hyperparameter_tuning_range:
      p: [1, 3]
      d: [1, 3]
      q: [1, 3]
      P: [0, 3]
      D: [0, 3]
      Q: [0, 3]
      s: [12, 12]

    # metric_to_use_when_tuning: 'MASE'
    metric_to_use_when_tuning: 'MAE'

    model_structure:
        - time_series_id: 2
          hyperparameters:
            p: 2
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 6
          hyperparameters:
            p: 3
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 9
          hyperparameters:
            p: 2
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 10
          hyperparameters:
            p: 3
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 11
          hyperparameters:
            p: 3
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 13
          hyperparameters:
            p: 3
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 20
          hyperparameters:
            p: 3
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 22
          hyperparameters:
            p: 0
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 24
          hyperparameters:
            p: 2
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 26
          hyperparameters:
            p: 2
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 27
          hyperparameters:
            p: 2
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 28
          hyperparameters:
            p: 3
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 29
          hyperparameters:
            p: 3
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 32
          hyperparameters:
            p: 2
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 33
          hyperparameters:
            p: 2
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 34
          hyperparameters:
            p: 3
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 39
          hyperparameters:
            p: 3
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 41
          hyperparameters:
            p: 3
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 51
          hyperparameters:
            p: 2
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4
        - time_series_id: 54
          hyperparameters:
            p: 2
            d: 1
            q: 0
            P: 5
            D: 1
            Q: 0
            s: 4