model:
  rng_seed: 42
  model_type: 'local_cnn_ae'
  model_config:
    forecast_window_size: 7
    steps_to_predict: 7
    multi_step_forecast: true # alternative is recursive single step
    auto_arima: true
    seasonal: true
    # Ranges used for autotuning if --tune parameter is set
    hyperparameter_tuning_range:
      p: [1, 3]
      d: [1, 3]
      q: [1, 3]
      P: [0, 3]
      D: [0, 3]
      Q: [0, 3]
      s: [12, 12]

    # metric_to_use_when_tuning: 'MASE'
    metric_to_use_when_tuning: 'MAE'

    model_structure:
      - time_series_id: 12322
        hyperparameters:
          p: 0
          d: 1
          q: 0
          P: 5
          D: 1
          Q: 0
          s: 4
      - time_series_id: 11428
        hyperparameters:
          p: 2
          d: 1
          q: 0
          P: 5
          D: 1
          Q: 0
          s: 4
      - time_series_id: 11850
        hyperparameters:
          p: 0
          d: 1
          q: 0
          P: 4
          D: 1
          Q: 0
          s: 4
      - time_series_id: 11852
        hyperparameters:
          p: 0
          d: 1
          q: 0
          P: 5
          D: 1
          Q: 1
          s: 4
      - time_series_id: 273
        hyperparameters:
          p: 2
          d: 1
          q: 0
          P: 5
          D: 1
          Q: 0
          s: 4
      - time_series_id: 11036
        hyperparameters:
          p: 0
          d: 1
          q: 0
          P: 5
          D: 1
          Q: 0
          s: 4
      - time_series_id: 11213
        hyperparameters:
          p: 0
          d: 1
          q: 1
          P: 5
          D: 1
          Q: 0
          s: 4
